testing workflow on push

diff --git a/.github/workflows/build-wheels.yml b/.github/workflows/build-wheels.yml
--- a/.github/workflows/build-wheels.yml
+++ b/.github/workflows/build-wheels.yml
@@ -10,6 +10,7 @@ on:
       tag:
         description: "Git tag to build (e.g. 3.6)"
         required: true
+        default: "3.6"
         type: string
       cmake_preset:
         description: "CMake preset (release, debug, relWithDebInfo)"
@@ -32,14 +33,14 @@ jobs:
       CMAKE_PRESET: ${{ github.event.inputs.cmake_preset }}
 
     steps:
-      - name: Validate cmake_preset
-        run: |
-          allowed=("release" "debug" "relWithDebInfo")
-          preset="${{ env.CMAKE_PRESET }}"
-          if [[ ! " ${allowed[@]} " =~ " ${preset} " ]]; then
-            echo "Error: invalid cmake_preset '${preset}'. Must be one of: ${allowed[*]}"
-            exit 1
-          fi
+#      - name: Validate cmake_preset
+#        run: |
+#          allowed=("release" "debug" "relWithDebInfo")
+#          preset="${{ env.CMAKE_PRESET }}"
+#          if [[ ! " ${allowed[@]} " =~ " ${preset} " ]]; then
+#            echo "Error: invalid cmake_preset '${preset}'. Must be one of: ${allowed[*]}"
+#            exit 1
+#          fi
 
       - name: Checkout tag
         uses: actions/checkout@v4
